"""LLM 연동. provider SDK 는 이 패키지 밖으로 새지 않는다."""

from app.integrations.llm.contracts import (
    DEFAULT_CATEGORY_HINTS,
    LOW_CONFIDENCE_THRESHOLD,
    AssetExtraction,
    ExtractedAsset,
    ExtractedTransaction,
    ParseMeta,
    ParseResult,
    TransactionCandidate,
    TransactionExtraction,
    TransactionSource,
    TransactionType,
    attach_source,
)
from app.integrations.llm.factory import get_escalation_client, get_llm_client
from app.integrations.llm.gemini import (
    GEMINI_DEFAULT_MODEL,
    GEMINI_ESCALATION_MODEL,
    GeminiStructuredClient,
)
from app.integrations.llm.openai import (
    OPENAI_DEFAULT_MODEL,
    OPENAI_ESCALATION_MODEL,
    OpenAiStructuredClient,
)
from app.integrations.llm.port import (
    LlmError,
    LlmImage,
    LlmInputError,
    LlmSchemaError,
    LlmStructuredClient,
    LlmUnavailableError,
    build_meta,
)
from app.integrations.llm.prompts import (
    ASSET_CAPTURE_MARKER,
    ASSET_TASK_MARKER,
    ASSET_TEXT_MARKER,
    RECEIPT_TASK_MARKER,
    SHARED_BOOK_MARKER,
    AssetHint,
    asset_capture_prompt,
    asset_text_prompt,
    for_shared_book,
    listed_asset_names,
    listed_categories,
    natural_language_prompt,
    receipt_prompt,
    retry_prompt,
    screenshot_prompt,
    with_assets,
)
from app.integrations.llm.stub import StubLlmStructuredClient

__all__ = [
    "ASSET_CAPTURE_MARKER",
    "ASSET_TASK_MARKER",
    "ASSET_TEXT_MARKER",
    "DEFAULT_CATEGORY_HINTS",
    "GEMINI_DEFAULT_MODEL",
    "GEMINI_ESCALATION_MODEL",
    "LOW_CONFIDENCE_THRESHOLD",
    "OPENAI_DEFAULT_MODEL",
    "OPENAI_ESCALATION_MODEL",
    "RECEIPT_TASK_MARKER",
    "SHARED_BOOK_MARKER",
    "AssetExtraction",
    "AssetHint",
    "ExtractedAsset",
    "ExtractedTransaction",
    "GeminiStructuredClient",
    "LlmError",
    "LlmImage",
    "LlmInputError",
    "LlmSchemaError",
    "LlmStructuredClient",
    "LlmUnavailableError",
    "OpenAiStructuredClient",
    "ParseMeta",
    "ParseResult",
    "StubLlmStructuredClient",
    "TransactionCandidate",
    "TransactionExtraction",
    "TransactionSource",
    "TransactionType",
    "asset_capture_prompt",
    "asset_text_prompt",
    "attach_source",
    "build_meta",
    "for_shared_book",
    "get_escalation_client",
    "get_llm_client",
    "listed_asset_names",
    "listed_categories",
    "natural_language_prompt",
    "receipt_prompt",
    "retry_prompt",
    "screenshot_prompt",
    "with_assets",
]
