"""initial schema

Revision ID: 9e46601ea881
Revises: 
Create Date: 2026-09-03 01:10:41.393292+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e46601ea881'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('anon_key_hash', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Seoul', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_anon_key_hash'), 'users', ['anon_key_hash'], unique=True)
    op.create_table('asset_snapshots',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('effective_on', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'screenshot', name='asset_source', native_enum=False, length=32), server_default='manual', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_asset_snapshots_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_snapshots'))
    )
    op.create_index('ix_asset_snapshots_user_id_effective_on', 'asset_snapshots', ['user_id', 'effective_on'], unique=False)
    op.create_table('budgets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('is_auto_carried', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_budgets_amount_non_negative')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_budgets_period_order')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('user_id', 'period_start', name='uq_budgets_user_id_period_start')
    )
    op.create_index('ix_budgets_user_id_period_start', 'budgets', ['user_id', 'period_start'], unique=False)
    op.create_table('categories',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('expense', 'income', 'transfer', name='category_kind', native_enum=False, length=32), server_default='expense', nullable=False),
    sa.Column('icon_key', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('uq_categories_user_id_name', 'categories', ['user_id', 'name'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('goals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('initial_amount', sa.Numeric(precision=14, scale=0), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('active', 'achieved', 'archived', name='goal_status', native_enum=False, length=32), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('initial_amount >= 0', name=op.f('ck_goals_initial_amount_non_negative')),
    sa.CheckConstraint('target_amount > 0', name=op.f('ck_goals_target_amount_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_index('uq_goals_user_id_active', 'goals', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.create_table('import_batches',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('keypad', 'nl', 'screenshot', 'receipt', 'asset_screenshot', 'no_spend', name='transaction_source', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'analyzing', 'ready', 'committed', 'failed', name='import_batch_status', native_enum=False, length=32), server_default='pending', nullable=False),
    sa.Column('detected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('committed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_batches_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index('ix_import_batches_user_id_created_at', 'import_batches', ['user_id', 'created_at'], unique=False)
    op.create_table('notification_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remind_at', sa.Time(), nullable=True),
    sa.Column('frequency', sa.Enum('weekly_twice', 'daily', name='notification_frequency', native_enum=False, length=32), server_default='weekly_twice', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Seoul', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_settings_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_settings_user_id'))
    )
    op.create_table('asset_items',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('asset_group', sa.Enum('cash', 'investment', 'deposit', 'debt', name='asset_group', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=0), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_asset_items_amount_non_negative')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['asset_snapshots.id'], name=op.f('fk_asset_items_snapshot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_items'))
    )
    op.create_index(op.f('ix_asset_items_snapshot_id'), 'asset_items', ['snapshot_id'], unique=False)
    op.create_table('category_budgets',
    sa.Column('budget_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_category_budgets_amount_non_negative')),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('fk_category_budgets_budget_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_budgets_category_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_budgets')),
    sa.UniqueConstraint('budget_id', 'category_id', name='uq_category_budgets_budget_id_category_id')
    )
    op.create_index(op.f('ix_category_budgets_budget_id'), 'category_budgets', ['budget_id'], unique=False)
    op.create_index(op.f('ix_category_budgets_category_id'), 'category_budgets', ['category_id'], unique=False)
    op.create_table('goal_contributions',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('source', sa.Enum('manual', 'asset_snapshot', name='goal_contribution_source', native_enum=False, length=32), server_default='manual', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_goal_contributions_amount_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_contributions_goal_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_contributions'))
    )
    op.create_index('ix_goal_contributions_goal_id_occurred_on', 'goal_contributions', ['goal_id', 'occurred_on'], unique=False)
    op.create_table('merchant_rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_normalized', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('applied_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_merchant_rules_category_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchant_rules_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_rules')),
    sa.UniqueConstraint('user_id', 'merchant_normalized', name='uq_merchant_rules_user_id_merchant_normalized')
    )
    op.create_index(op.f('ix_merchant_rules_category_id'), 'merchant_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_merchant_rules_user_id'), 'merchant_rules', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('type', sa.Enum('expense', 'income', 'transfer', 'refund', name='transaction_type', native_enum=False, length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merchant', sa.String(length=120), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('keypad', 'nl', 'screenshot', 'receipt', 'asset_screenshot', 'no_spend', name='transaction_source', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('excluded_from_budget', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('refund_of_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("amount > 0 OR source = 'no_spend'", name=op.f('ck_transactions_amount_positive')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_transactions_confidence_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_transactions_import_batch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['refund_of_transaction_id'], ['transactions.id'], name=op.f('fk_transactions_refund_of_transaction_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_import_batch_id'), 'transactions', ['import_batch_id'], unique=False)
    op.create_index('ix_transactions_user_id_fingerprint', 'transactions', ['user_id', 'fingerprint'], unique=False)
    op.create_index('ix_transactions_user_id_occurred_at', 'transactions', ['user_id', 'occurred_at'], unique=False)
    op.create_index('ix_transactions_user_id_type_occurred_at', 'transactions', ['user_id', 'type', 'occurred_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('budget_auto_carryover', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('home_hero', sa.Enum('remaining_budget', 'income_expense', 'income_and_budget', name='home_hero', native_enum=False, length=32), server_default='remaining_budget', nullable=False),
    sa.Column('last_record_method', sa.Enum('keypad', 'nl', 'screenshot', 'receipt', name='record_method', native_enum=False, length=32), nullable=True),
    sa.Column('report_include_income', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('happy_spend_category_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['happy_spend_category_id'], ['categories.id'], name=op.f('fk_user_preferences_happy_spend_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id'))
    )
    op.create_table('import_candidates',
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=0), nullable=False),
    sa.Column('type', sa.Enum('expense', 'income', 'transfer', 'refund', name='transaction_type', native_enum=False, length=32), nullable=False),
    sa.Column('merchant', sa.String(length=120), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_import_candidates_amount_positive')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_import_candidates_confidence_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_import_candidates_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_import_candidates_import_batch_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_import_candidates_transaction_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_candidates'))
    )
    op.create_index(op.f('ix_import_candidates_fingerprint'), 'import_candidates', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_import_candidates_import_batch_id'), 'import_candidates', ['import_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_candidates_import_batch_id'), table_name='import_candidates')
    op.drop_index(op.f('ix_import_candidates_fingerprint'), table_name='import_candidates')
    op.drop_table('import_candidates')
    op.drop_table('user_preferences')
    op.drop_index('ix_transactions_user_id_type_occurred_at', table_name='transactions')
    op.drop_index('ix_transactions_user_id_occurred_at', table_name='transactions')
    op.drop_index('ix_transactions_user_id_fingerprint', table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_batch_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_merchant_rules_user_id'), table_name='merchant_rules')
    op.drop_index(op.f('ix_merchant_rules_category_id'), table_name='merchant_rules')
    op.drop_table('merchant_rules')
    op.drop_index('ix_goal_contributions_goal_id_occurred_on', table_name='goal_contributions')
    op.drop_table('goal_contributions')
    op.drop_index(op.f('ix_category_budgets_category_id'), table_name='category_budgets')
    op.drop_index(op.f('ix_category_budgets_budget_id'), table_name='category_budgets')
    op.drop_table('category_budgets')
    op.drop_index(op.f('ix_asset_items_snapshot_id'), table_name='asset_items')
    op.drop_table('asset_items')
    op.drop_table('notification_settings')
    op.drop_index('ix_import_batches_user_id_created_at', table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index('uq_goals_user_id_active', table_name='goals', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index('uq_categories_user_id_name', table_name='categories', postgresql_nulls_not_distinct=True)
    op.drop_table('categories')
    op.drop_index('ix_budgets_user_id_period_start', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_asset_snapshots_user_id_effective_on', table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    op.drop_index(op.f('ix_users_anon_key_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
