"""분석 사용량 기록과 상호 규칙의 표기용 이름

parse_usages 는 줄글·캡처 분석을 몇 번 불렀는지만 센다. 원문은 담지 않는다.
비용을 재 보고 나서 상한을 정하려고 만든 표다.

merchant_rules.merchant 는 화면에 그대로 보여 줄 표기다. 정규화된 값만 들고 있으면
규칙 목록에 띄어쓰기와 대소문자가 사라진 이름이 보인다. 기존 행이 없어 nullable 로 둔다.

Revision ID: bcf9baa5e4fd
Revises: c4a1b8f2d7e3
Create Date: 2026-09-04 16:31:47.615668+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf9baa5e4fd'
down_revision: Union[str, Sequence[str], None] = 'c4a1b8f2d7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('parse_usages',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('keypad', 'nl', 'screenshot', 'receipt', 'asset_screenshot', 'no_spend', name='transaction_source', native_enum=False, length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('is_stub', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('input_length', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('redacted_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('candidate_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_parse_usages_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_usages'))
    )
    op.create_index('ix_parse_usages_user_id_created_at', 'parse_usages', ['user_id', 'created_at'], unique=False)
    op.add_column('merchant_rules', sa.Column('merchant', sa.String(length=120), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_rules', 'merchant')
    op.drop_index('ix_parse_usages_user_id_created_at', table_name='parse_usages')
    op.drop_table('parse_usages')
